/**
 * DO NOT EDIT THIS FILE.
 * @preserve
 **/

(function ($, window, Drupal, once) {
  Drupal.behaviors.gentilClaro = {
    attach: function attach(context, settings) {

      once("gentilGmooltip", "[data-gmooltip]", context).forEach(
        this.setUpGmooltip
      );
      once("gentilBioMore", "[data-bio-more]", context).forEach(
        this.setupBioMore
      );
      once("gentilIntenseImage", "[data-clk-oo]", context).forEach(
        this.setOoLink
      );
      once("gentilIntenseImage", "body", context).forEach(
        this.setupGentilProgressBaarr
      );

    },

    setupBioMore: function (item) {
      if (item.children.length > 1) {
        if (item.children && item.children[0]) {
          item.setAttribute("data-bio-more-status", false);
          let icon = document.createElement("i");
          icon.className = "i-gntl i-gntl--add";

          let a = document.createElement("a");
          a.append(icon);

          // let title = document.createElement("span");
          // title.append(Drupal.t('Déplier la description'));
          // title.className = "visually-hidden";
          // a.append(title);

          a.className = "ff-view-more";
          a.setAttribute("title", Drupal.t("Lire toute biographie"));
          a.setAttribute(
            "uk-tooltip",
            "title:" + Drupal.t("Lire toute biographie") + ";pos: bottom-right"
          );
          a.setAttribute("href", "#");

          a.addEventListener("click", function (e) {
            e.preventDefault();
            let wrapper = this.parentNode ? this.parentNode : null;
            if (wrapper) {
              let statusBio =
                wrapper.dataset && wrapper.dataset.bioMoreStatus === "false"
                  ? true
                  : false;
              if (statusBio) {
                let titleClose = Drupal.t("Fermer la biographie");
                this.setAttribute("title", titleClose);
                this.setAttribute(
                  "uk-tooltip",
                  "title:" + titleClose + ";pos: bottom-right"
                );
                this.parentNode.setAttribute("data-bio-more-status", true);
                this.firstChild.className = "i-gntl i-gntl--clear";
              } else {
                let titleOpen = Drupal.t("Lire toute biographie");
                this.setAttribute("title", titleOpen);
                this.setAttribute(
                  "uk-tooltip",
                  "title:" + titleOpen + ";pos: bottom-right"
                );
                this.parentNode.setAttribute("data-bio-more-status", false);
                this.firstChild.className = "i-gntl i-gntl--add";
              }
            }
          });
          item.append(a);
        }
      }
    },

    setupGentilProgressBaarr: function (idx, column) {
      window.onscroll = function () {
        Drupal.gentilClaroApp.app.scollProgress();
      };
    },
    setOoLink: function (item, idx) {
      let link = item.querySelector('[data-clk-oo-target]');
      if (link) {
        item.addEventListener('click', () => {
          location.href = link.dataset.clkOoTarget;
          console.log('link', link.dataset.clkOoTarget)
        });
      }

    },

    setUpGmooltip: function (item) {
      let gmooltip =
        item.dataset && item.dataset.gmooltip
          ? item.dataset.gmooltip.trim()
          : false;

      let titleGmooltip = "";
      let positionGmooltip = "top";

      if (gmooltip) {
        let dataGmooltip = gmooltip.split(";");
        dataGmooltip.forEach((element) => {
          let attrGmooltip = element.trim();
          let datasGmooltipAttrs = attrGmooltip.split(":");
          if (datasGmooltipAttrs[0].trim() === "title") {
            titleGmooltip = datasGmooltipAttrs[1].trim();
          }
          if (datasGmooltipAttrs[0].trim() === "pos") {
            positionGmooltip = datasGmooltipAttrs[1].trim();
          }
        });
      }

      let tooltipDiv = document.createElement("div");
      tooltipDiv.className = `i-tooltip i-tooltip-${positionGmooltip} uk-animation-slide-left-small`;
      let tooltipDivWrapper = document.createElement("div");
      tooltipDivWrapper.className = "i-tooltip-wrapper";
      let tooltipSpan = document.createElement("span");
      tooltipSpan.className = "i-tooltip-span";
      tooltipSpan.append(titleGmooltip);
      tooltipDivWrapper.append(tooltipSpan);
      tooltipDiv.append(tooltipDivWrapper);

      ["focusin", "hover", "pointerleave", "pointerenter", "blur"].forEach(
        (type) => {
          switch (type) {
            case "focusin":
            case "pointerover":
            case "pointerenter":
              item.addEventListener(type, () => {
                item.parentNode.prepend(tooltipDiv);
              });
              break;
            case "pointerleave":
            case "blur":
              item.addEventListener(type, () => {
                tooltipDiv.remove();
              });
              break;

            default:
              break;
          }
        }
      );
    },
  };

  /**
   * Namespace for gentilClaroApp related functionality.
   *
   * @namespace
   */
  Drupal.gentilClaroApp = {
    /**
     * A {@link Drupal.gentilClaroApp.App} instance.
     */
    app: {},

    // dsettings: drupalSettings,
  };

  Drupal.gentilClaroApp.app = {
    initializeCollection: function (context) {
      // define gentilClaroApp
      var App = Drupal.gentilClaroApp;
      $("#a42-ac-button").attr("uk-icon", "world");
      // console.log('App', App);
      // console.log(Drupal.gentilClaroApp.dsettings.path.currentLanguage);
      // var locale = Drupal.gentilClaroApp.dsettings.path.currentLanguage;
    },

    scollProgress: function () {
      var winScroll =
        document.body.scrollTop || document.documentElement.scrollTop;
      var height =
        document.documentElement.scrollHeight -
        document.documentElement.clientHeight;
      var scrolled = (winScroll / height) * 100;
      var progressBar = document.getElementById("progress-bar");
      if (progressBar) {
        progressBar.style.width = scrolled + "%";
      }
    },
  };
})(jQuery, window, Drupal, once);






