/**
 * DO NOT EDIT THIS FILE.
 * @preserve
 **/
(($, Drupal, once) => {
  Drupal.behaviors.gentilMenus = {
    attach(context) {
      once("gentilMenusLoad", "button[data-menus]", context).forEach(
        (value) => {
          const input = $(value);
          console.log("hello");
          value.setAttribute("aria-controls", value.dataset.ariacontrols);
          value.addEventListener("click", (e) =>
            toggleMenuState(e.currentTarget, !getMenuState(e.currentTarget))
          );
        }
      );

      /**
       * Toggles the aria-expanded attribute of a given button to a desired state.
       * @param {element} button - Button element that should be toggled.
       * @param {boolean} toState - State indicating the end result toggle operation.
       */
      function toggleMenuState(button, toState) {
        button.setAttribute("aria-expanded", toState);
      }
      /**
       * Get the current aria-expanded state of a given button.
       * @param {element} button - Button element to return state of.
       */
      function getMenuState(button) {
        return button.getAttribute("aria-expanded") === "true";
      }
    },
  };
})(jQuery, Drupal, once);
