<?php

/**
 * Implements hook_preprocess_page().
 */
function opencar_access_preprocess_html(&$variables) {
  //$getScheme = \Drupal::request();
  //$variables['is_back'] = str_starts_with($getScheme->getHost(), 'bck') ? TRUE : FALSE;
  //if (\Drupal::currentUser()->isAuthenticated()) {
  //  if (!str_starts_with($getScheme->getHost(), 'bck')) {
  //    user_logout();
  //  }
  //}
}

/**
 * Implements hook_preprocess_page().
 */
function opencar_access_preprocess_page(&$variables) {
  $getScheme = \Drupal::request();
  $variables['is_back'] = str_starts_with($getScheme->getHost(), 'bck') ? TRUE : FALSE;
}

/**
 * Implements hook_preprocess_node().
 */
function opencar_access_preprocess_node(&$variables) {
  $getScheme = \Drupal::request();
  $variables['is_back'] = str_starts_with($getScheme->getHost(), 'bck') ? TRUE : FALSE;
}

/**
 * Implements hook_menu_local_tasks_alter().
 *
 * Changes weight and access for the 'Log out' tab on the user page.
 */
function opencar_access_menu_local_tasks_alter(&$data, $route_name, &$cacheability) {
  if (isset($data['tabs'][0]['entity.user.deconnexion'])) {
    $tab_data = &$data['tabs'][0]['entity.user.deconnexion'];
    $link_params = $tab_data['#link']['url']->getRouteParameters();
    $tab_data['#access'] = $link_params['user'] == \Drupal::currentUser()->id();
    if ($tab_data['#access']) {
      $tab_data['#weight'] = 99;
    }
  }
}
